version: "3"

services:
  mongo:
    container_name: mongo-container
    image: mongo:latest
    restart: always
    volumes: 
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:lts
    working_dir: /usr/src/clean-node-api
    command: bash -c "npm install --omit=dev && npm run debug"
    ports:
      - "5050:5050"
      - "9222:9222"
    restart: always
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json
    links:
      - mongo
    